### ISSUE TITLE
Failure reading binary VDF files

### ISSUE THREAD

**Issue by barraponto** [ValvePython/vdf#13]
When I try to read binary files such as `appcache/appinfo.vdf` or `appcache/packageinfo.vdf`, I always see the same error: 

> SyntaxError: Unknown data type at index 5: b"'"

I tried using `alt_format=True` but it just errors too :/

```python
import vdf
with open('~/.steam/root/appcache/appinfo.vdf', 'rb') as appinfo:
    data = vdf.binary_lods(appinfo.read())
```

**Comment by rossengeorgiev** [comment]
The extension says `vdf`, but it is actually a custom format that has vdf sections for each app.

**Comment by EhsanKia** [comment]
Any hint on how to parse it then?

**Comment by EhsanKia** [comment]
Seems like appinfo has a new format recently (january 2017). Parser for it would be highly appreciated.

**Comment by rossengeorgiev** [comment]
I had a look around and the format is as follows:

### appinfo format
```text
uint32   - MAGIC: "'DV\x07"
uint32   - UNIVERSE: 1
---- repeated app sections ----
uint32   - AppID
uint32   - size
uint32   - infoState 
uint32   - lastUpdated
uint64   - accessToken
20bytes  - SHA1
uint32   - changeNumber
variable - binary_vdf
---- end of section ---------
uint32   - EOF: 0
```

### packageinfo

```text
uint32   - MAGIC: "'UV\x06"
uint32   - UNIVERSE: 1
---- repeated app sections ----
uint32   - PackageID
20bytes - SHA1
uint32   - changeNumber
variable - binary_vdf
---- end of section ---------
uint32   - EOF: 0xFFFFFFFF

**Comment by rossengeorgiev** [comment]
Current beta client has updated the format:

### packageinfo

```text
uint32   - MAGIC: "'UV\x06"
uint32   - UNIVERSE: 1
---- repeated package sections ----
uint32   - PackageID
20bytes  - SHA1
uint32   - changeNumber
uint64   - token
variable - binary_vdf
---- end of section ---------
uint32   - EOF: 0xFFFFFFFF

**Comment by xPaw** [comment]
I wrote some C# code to fully parse these files if anyone is interested: https://github.com/SteamDatabase/SteamAppInfo

**Comment by rossengeorgiev** [comment]
`steam` package now implements methods for parsing these files in `steam.utils.appcache`. 

https://github.com/ValvePython/steam/issues/179
