### ISSUE TITLE
Arch User Repository packages

### ISSUE THREAD

**Issue by vanyasem** [ValvePython/vdf#14]
I packaged `python-vdf` for Arch GNU/Linux in AUR:

Packages: [python2-vdf-git](https://aur.archlinux.org/packages/python2-vdf-git/), [python-vdf-git](https://aur.archlinux.org/packages/python-vdf-git/), [python2-vdf](https://aur.archlinux.org/packages/python2-vdf/), [python-vdf](https://aur.archlinux.org/packages/python-vdf/)

Packages suffixed with `-git` are built from git source, others are built from the lastest release tarball

Packages prefixed with `python-` are built for Python 3.x, and prefixed with `python2-` are built for Python 2.x

You can install them using any AUR helper (the recommended one is `pacaur`):
```
pacaur -S python-vdf
```

You can also install them manually:
```
git clone https://aur.archlinux.org/python-vdf.git
cd python-vdf
makepkg -sic
```

It would be great if you added them to your readme

**Comment by rossengeorgiev** [comment]
That's great. Advertising the package on AUR in the README may give the false impression that this project is responsible for it, which is not the case. In the future, if there is a section for listing similar projects, I will make sure to include it.

**Comment by vanyasem** [comment]
Hey! It was almost a full year since I created the issue. You ruined it, it was only 3 days left :P Just joking, I totally understand you reasoning behind this - still worth giving a mention with a huge "unofficial" tag though imo
