### ISSUE TITLE
Building python-vdf version 3.3 with python 3.10 fails

### ISSUE THREAD

**Issue by rhabacker** [ValvePython/vdf#46]
Building python-vdf version 3.3 with python 3.10 at at https://build.opensuse.org/package/show/games:tools/python-vdf fails with the following error: 
+ /usr/bin/python3.10 setup.py build '--executable=/usr/bin/python3.10 -s'
[   50s] Traceback (most recent call last):
[   50s]   File "/home/abuild/rpmbuild/BUILD/python-vdf-3.3/setup.py", line 6, in <module>
[   50s]     import vdf
[   50s]   File "/home/abuild/rpmbuild/BUILD/python-vdf-3.3/vdf/__init__.py", line 19, in <module>
[   50s]     from vdf.vdict import VDFDict
[   50s]   File "/home/abuild/rpmbuild/BUILD/python-vdf-3.3/vdf/vdict.py", line 9, in <module>
[   50s]     class _kView(_c.KeysView):
[   50s] AttributeError: module 'collections' has no attribute 'KeysView'
[   50s] error: Bad exit status from /var/tmp/rpm-tmp.kZk3A8 (%build)

**Comment by rossengeorgiev** [comment]
Strange error message `AttributeError: module 'collections' has no attribute 'KeysView'`. It says `collections` not `collections.abc`. And `KeysView` is definitely still there https://docs.python.org/3.10/library/collections.abc.html#collections.abc.KeysView

I'm guessing the following statement no longer works as expected: https://github.com/ValvePython/vdf/blob/8104cb27c0b222bd802b69df58204ab389fc714c/vdf/vdict.py#L8

Perhaps it ignores everything after the dot, in which case it should be changed to `from collections import abc as _c`.

**Comment by rossengeorgiev** [comment]
Tests seem to pass without changing anything for `3.10`: https://github.com/ValvePython/vdf/runs/5578350909?check_suite_focus=true#step:6:29

**Comment by rhabacker** [comment]
You are probably using git master or the latest version 3.4 ? 

At least with version 3.4 I can confirm that the error is gone. Thanks for your support.

**Comment by rossengeorgiev** [comment]
Yes, I was testing latest, and somehow glanced over `3.3` being mentioned. Yes, the issue is present in there https://github.com/ValvePython/vdf/blob/v3.3/vdf/vdict.py#L8
